#!/usr/bin/env python
import sys
from pprint import pprint

from pycompiler.parser import PythonParser
from pycompiler.analyzer import PythonAnalyzer
from pycompiler.compiler import PythonCompiler


if len(sys.argv) != 3:
    print """
Usage: pycompiler (parse|ast|compile) file.py
    """

command, path = sys.argv[1:]

parser = PythonParser()

tokens = parser.parse(open(path).read())

print 'Tokens:'
pprint(tokens)
if command == 'parse':
    sys.exit(0)


analyzer = PythonAnalyzer(tokens)
ast = analyzer.run()

print 'AST:'
print ast.to_string()
if command == 'parse':
    sys.exit(0)

print 'Bytecode:'

compiler = PythonCompiler()
compiler.compile(ast)
compiler.write(open(path + '.pyc', 'w'))